project:
  #type: book
  type: website
  output-dir: docs

toc: true
toc-location: right
number-sections: false
#bibliography: assets/references.bib

execute:
  enabled: true


website:
  title: "nba"
  navbar:
    right:
      - index.ipynb
      - icon: github
        href: draft.ipynb
      - icon: twitter
        href: main2.ipynb
format:
  html:
    #theme: cosmo
    css: assets/styles.css



